#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "Engine builders — Hetzner and GitHub"

# ── 1. Where this runs ─────────────────────────────────────────────────────
stage "Check where we are"
say "The secrets belong to the repository that holds the build workflow,"
say "which is omaweb-qtwebengine-patches. gh writes them to whichever"
say "repository this shell is in."
printf '\n'
repo=$(gh repo view --json nameWithOwner --jq .nameWithOwner 2>/dev/null || echo "none")
step "gh says this directory is: $repo"
if [[ "$repo" != *"omaweb-qtwebengine-patches" ]]; then
  warn "Run this from a clone of omaweb-qtwebengine-patches, then start again."
  exit 1
fi
for tool in ssh-keygen curl; do
  command -v "$tool" >/dev/null 2>&1 || { warn "$tool is missing"; exit 1; }
done
step "ssh-keygen and curl are here."
pause "Good?"

# ── 2. Hetzner project and token ───────────────────────────────────────────
stage "Hetzner — a project of its own"
say "A Hetzner token is scoped to one project and nothing finer, so the"
say "project is the blast radius. Builders live alone in theirs."
open_url "https://console.hetzner.com/projects"
step "Create a project called omaweb-builds, then open it."
step "Security → API tokens → Generate API token."
step "Give it Read & Write. Copy it now: Hetzner shows it once."
ask_secret HCLOUD_TOKEN "Paste the token:"
if curl -fsS -H "Authorization: Bearer $HCLOUD_TOKEN" \
     "https://api.hetzner.cloud/v1/servers" >/dev/null 2>&1; then
  step "The token works."
else
  warn "Hetzner refused that token. Check it and run this stage again."
fi
write_env HCLOUD_TOKEN "$HCLOUD_TOKEN"
set_secret HCLOUD_TOKEN "$HCLOUD_TOKEN"
pause "Token stored. Next?"

# ── 3. A keypair for builders only ─────────────────────────────────────────
stage "A key that only ever opens rented machines"
say "This key reaches machines that exist for a few hours and are then"
say "deleted. It is not your personal key, and it never signs anything."
key_path="$HOME/.ssh/omaweb-builder"
if [[ -f "$key_path" ]]; then
  step "Found one already at $key_path, keeping it."
else
  ssh-keygen -t ed25519 -f "$key_path" -N "" -C "omaweb-builder" >/dev/null
  step "Generated $key_path."
fi
set_secret BUILDER_SSH_KEY "$(cat "$key_path")"
printf '\n'
say "The public half, which Hetzner needs in the next stage:"
printf '\n%s\n\n' "$(cat "$key_path.pub")"
pause "Copy that line, then continue."

# ── 4. Teach Hetzner the key ───────────────────────────────────────────────
stage "Hetzner — add the builder key"
open_url "https://console.hetzner.com/projects"
step "Open the omaweb-builds project → Security → SSH keys → Add SSH key."
step "Paste the public key you just copied."
step "Name it omaweb-builder, or anything you like."
ask BUILDER_SSH_KEY_NAME "What did you name it? [omaweb-builder]"
BUILDER_SSH_KEY_NAME="${BUILDER_SSH_KEY_NAME:-omaweb-builder}"
write_env OMAWEB_SSH_KEY "$BUILDER_SSH_KEY_NAME"
set_var BUILDER_SSH_KEY_NAME "$BUILDER_SSH_KEY_NAME"
pause "Key uploaded?"

# ── 5. A token that can open issues in omaweb ──────────────────────────────
stage "GitHub — a token for issues in omaweb"
say "The daily series check reports to the Omaweb tracker, because one"
say "place should hold everything that needs a person. A workflow token"
say "cannot cross repositories, so this is a fine-grained PAT that can do"
say "one thing."
open_url "https://github.com/settings/personal-access-tokens/new"
step "Resource owner: villekivela. Repository access: only villekivela/omaweb."
step "Repository permissions → Issues → Read and write. Nothing else."
step "Give it an expiry you will notice, then generate and copy it."
ask_secret OMAWEB_ISSUES_TOKEN "Paste the token:"
if curl -fsS -H "Authorization: Bearer $OMAWEB_ISSUES_TOKEN" \
     "https://api.github.com/repos/villekivela/omaweb" >/dev/null 2>&1; then
  step "The token can see omaweb."
else
  warn "GitHub refused that token, or it cannot see the repository."
fi
set_secret OMAWEB_ISSUES_TOKEN "$OMAWEB_ISSUES_TOKEN"
pause "Stored. One stage left."

# ── 6. Check what the workflows will find ──────────────────────────────────
stage "Check it from the workflow's side"
say "These are the names build-engine.yml and series-applies.yml ask for."
printf '\n'
gh secret list 2>/dev/null | sed 's/^/  /' || warn "could not list secrets"
printf '\n'
gh variable list 2>/dev/null | sed 's/^/  /' || true
printf '\n'
say "Two things worth doing by hand, in the Hetzner console:"
step "Check the project's server limit, so a loop cannot rent fifty machines."
step "Set a spend alert on the account."
printf '\n'
say "Then a build is one dispatch:"
step "gh workflow run build-engine.yml -f version=6.11.2 -f arch=both"

finish
